-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Company"
(

    CONSTRAINT "Company_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Department"
(

    CONSTRAINT "Department_pkey" PRIMARY KEY (depid)
);

CREATE TABLE IF NOT EXISTS public."Employee"
(

    CONSTRAINT "Employee_pkey" PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."Company"
    ADD CONSTRAINT "Company_dpid_fkey" FOREIGN KEY (dpid)
    REFERENCES public."Department" (depid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Department"
    ADD CONSTRAINT "Department_empid_fkey" FOREIGN KEY (empid)
    REFERENCES public."Employee" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;